name: 'devbox installer'
description: 'Install Devbox in your CICD workflow'

runs:
  using: "composite"
  steps:
    - name: Install devbox
      uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 #v0.15.0
      with:
        project-path: ./test
        enable-cache: true
        devbox-version: 0.17.5
        sha256-checksum: 520abeaca5fb8e8175bea2acdaac4109e87768ac25ad8da5ad2e6eace5a6060b # devbox_0.17.5_linux_amd64.tar.gz
