name: Test devbox plugin terraform-cicd

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
    paths:
      - 'plugin.json'
      - 'config/**'
      - 'scripts/**'
      - 'test/**'
      - '.github/workflows/test-terraform-cicd.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  test:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        setup:
          - include: "path:../plugin.json"
            name: "Test with plugin from local path"
          - include: "github:${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
            name: "Test with plugin from GitHub"
    name: ${{ matrix.setup.name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: update include within devbox.json
        if: ${{ matrix.setup.include != 'path:../plugin.json' }}
        shell: bash
        run: |
          set -euo pipefail
          sed -i "s|\"path:../plugin.json\"|\"${INCLUDE}\"|g" devbox.json
        env:
          INCLUDE: ${{ matrix.setup.include }}

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main  # v21
        with:
          logger: pretty
          extra-conf: experimental-features = ca-derivations fetch-closure
          summarize: false

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          project-path: ./test
          enable-cache: true
          devbox-version: 0.16.0
          skip-nix-installation: true

      - name: verify missing variable
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env_missing plan  2>&1 | tee error.log
          if ! grep -q "The root module input variable \"test\" is not set, and has no default value." error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: changes

      - name: verify plan with changes
        uses: ./action
        with:
          workdir: changes
          config-file: config/.env
          command: plan
          devboxdir: ./test

      - name: verify apply with changes
        uses: ./action
        with:
          workdir: changes
          config-file: config/.env
          command: apply
          devboxdir: ./test
      
      - name: verify plan-and-apply with changes
        uses: ./action
        with:
          workdir: changes
          config-file: config/.env
          command: plan-and-apply
          devboxdir: ./test

      - name: verify plan without changes
        uses: ./action
        with:
          workdir: nochanges
          config-file: config/.env
          command: plan
          devboxdir: ./test

      - name: verify apply without changes
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env apply 2>&1 | tee error.log
          set -e
          if ! grep -q "No tfplan file found. Please run 'devbox run plan' first." error.log; then
            echo "No tfplan file found. Please run 'devbox run plan' first."
            exit 1
          fi
        env:
          WORKDIR: nochanges

      - name: verify plan-and-apply without changes
        uses: ./action
        with:
          workdir: nochanges
          config-file: config/.env
          command: plan-and-apply
          devboxdir: ./test

      - name: verify plan/apply/plan-and-apply without config
        run: |
          set +e
          devbox run --env-file noconfig/config/.env plan 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: open noconfig/config/.env: no such file or directory" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noconfig

      - name: verify plan without terraform config
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env plan 2>&1 | tee error.log
          set -e
          if ! grep -q "Error running terraform plan." error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noterraform

      - name: verify plan-and-apply without terraform config
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env plan-and-apply 2>&1 | tee error.log
          set -e
          if ! grep -q "Error running terraform plan." error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noterraform

      - name: verify plan-and-apply without terraform config
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env plan-and-apply 2>&1 | tee error.log
          set -e
          if ! grep -q "Error running terraform plan." error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noterraform

      - name: verify check-quality with bad validate
        run: |
          set +e
          devbox run check-quality 2>&1 | tee error.log
          set -e
          if ! grep -q "can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: badvalidate

      - name: verify check-quality with bad format
        run: |
          set +e
          devbox run check-quality 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: error running script \"check-quality\" in Devbox: exit status 3" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: badformat

      - name: verify check-quality with bad trivy
        run: |
          set +e
          devbox run check-quality 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: error running script \"check-quality\" in Devbox: exit status 2" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: badtrivy

      - name: verify check-quality with bad tflint
        run: |
          set +e
          devbox run check-quality 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: error running script \"check-quality\" in Devbox: exit status 2" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: badtflint

      - name: verify check-quality with bad readme
        run: |
          set +e
          devbox run check-quality 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: README.md is out of date" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: badreadme
