name: Test devbox plugin terraform-cicd

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
    paths:
      - 'plugin.json'
      - 'config/**'
      - 'test/**'
      - '.github/workflows/test-terraform-cicd.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v6

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          project-path: test
          enable-cache: true
          devbox-version: 0.16.0

      - name: verify missing variable
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env_missing plan  2>&1 | tee error.log
          if ! grep -q "The root module input variable \"test\" is not set, and has no default value." error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: changes

      - name: verify plan with changes
        run: devbox run --env-file $WORKDIR/config/.env plan
        env:
          WORKDIR: changes
      
      - name: verify apply with changes
        run: devbox run --env-file $WORKDIR/config/.env apply
        env:
          WORKDIR: changes
      
      - name: verify plan-and-apply with changes
        run: devbox run --env-file $WORKDIR/config/.env plan-and-apply
        env:
          WORKDIR: changes
          AUTO_APPROVE: true

      - name: verify plan without changes
        run: devbox run --env-file $WORKDIR/config/.env plan
        env:
          WORKDIR: nochanges

      - name: verify apply without changes
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env apply 2>&1 | tee error.log
          set -e
          if ! grep -q "No tfplan file found. Please run 'devbox run plan' first." error.log; then
            echo "No tfplan file found. Please run 'devbox run plan' first."
            exit 1
          fi
        env:
          WORKDIR: nochanges

      - name: verify plan-and-apply without changes
        run: devbox run --env-file $WORKDIR/config/.env plan-and-apply
        env:
          WORKDIR: nochanges
          AUTO_APPROVE: true

      - name: verify plan/apply/plan-and-apply without config
        run: |
          set +e
          devbox run --env-file noconfig/config/.env plan 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: open noconfig/config/.env: no such file or directory" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noconfig

      - name: verify plan without terraform config
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env plan 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: No configuration files" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noterraform

      - name: verify plan-and-apply without terraform config
        run: |
          set +e
          devbox run --env-file $WORKDIR/config/.env plan-and-apply 2>&1 | tee error.log
          set -e
          if ! grep -q "Error: No configuration files" error.log; then
            echo "Expected error message not found in output."
            exit 1
          fi
        env:
          WORKDIR: noterraform
          AUTO_APPROVE: true

