name: Update cache of devbox and nix for terraform-cicd plugin

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'test/devbox.json'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  update-cache:
    name: Update cache for devbox plugin terraform-cicd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 #v0.15.0
        with:
          project-path: ./test
          enable-cache: true
          devbox-version: 0.17.2
