name: Update cache of devbox and nix for terraform-cicd plugin

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'test/devbox.json'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  update-cache:
    name: Update cache for devbox plugin terraform-cicd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install devbox
        uses: ./.github/actions/install-devbox
