name: Update cache of devbox and nix for terraform-cicd plugin

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'test/devbox.json'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  update-cache:
    name: Update cache for devbox plugin terraform-cicd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install devbox
        uses: ./.github/actions/install-devbox
